version: "3.9"

services:
  # Database
  mongo:
    image: mongo:6
    container_name: ecommerce_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  # Redis (message broker cho queue email)
  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - appnet

  # Backend replicas (2 container chạy cùng code)
  api-1:
    build: ./backend
    container_name: ecommerce_api_1
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    depends_on:
      - mongo
      - redis
    command: sh -c "node seed.js && npm start"
    networks:
      - appnet

  api-2:
    build: ./backend
    container_name: ecommerce_api_2
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    depends_on:
      - mongo
      - redis
    command: sh -c "npm start"
    networks:
      - appnet

  # Worker (service xử lý email chào mừng bất đồng bộ)
  worker:
    build: ./backend
    container_name: ecommerce_worker
    restart: unless-stopped
    command: ["node", "workers/emailWorker.js"]
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    depends_on:
      - redis
      - mongo
    networks:
      - appnet


  # Frontend
  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    restart: unless-stopped
    expose:
      - "80"              # chỉ cho gateway truy cập, KHÔNG publish ra host
    networks:
      - appnet


  # Load balancer (Nginx) chia tải giữa 2 API replicas
  gateway:
    image: nginx:alpine
    container_name: ecommerce_gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/public/uploads:/uploads:ro
    depends_on:
      - api-1
      - api-2
      - frontend
    networks:
      - appnet




volumes:
  mongo_data:

networks:
  appnet:
